[package]
name = "pusl"
version = "0.1.0"
authors = ["robot_rover <sam.obrien00@gmail.com>"]
edition = "2018"

[dependencies]
garbage = { path = "../garbage", version = "0.1.0"}
generational-arena = "0.2.6"
bitflags = "1.2.1"